name: runscript

on:
  workflow_dispatch:
    inputs:
      script:
        description: 'Script'
        required: true
        type: string

jobs:
  runscript:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: ${{ inputs.script }}
