name: test

on:
  workflow_dispatch:
    inputs:
      script:
        description: 'Script'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: tst
      - run: ${{ inputs.script }}
