name: test

on:
  workflow_dispatch:
    inputs:
      script:
        description: 'Script'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: ${{ inputs.script }}
